server: 
  port: 8081
  servlet: 
    context-path: /sample-resource-server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/csor-auth
          jwk-set-uri: http://localhost:9080/csor-oauth/oauth2/jwks